# Generated by Django 3.2.25 on 2026-07-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='账户余额'),
        ),
    ]
