# Generated by Django 3.2.25 on 2026-06-21 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='价格(元)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('call_limit', models.IntegerField(default=0, verbose_name='调用次数限制(0=不限)')),
                ('token_limit', models.BigIntegerField(default=0, verbose_name='Token量限制(0=不限)')),
                ('duration_type', models.CharField(choices=[('day', '天'), ('month', '月'), ('year', '年'), ('forever', '永久')], default='month', max_length=10, verbose_name='期限类型')),
                ('duration_value', models.IntegerField(default=1, verbose_name='期限值')),
                ('model_restrict', models.BooleanField(default=False, verbose_name='限制模型')),
                ('model_ids', models.JSONField(blank=True, default=list, verbose_name='可用模型ID列表')),
                ('status', models.CharField(choices=[('enabled', '上架'), ('disabled', '下架')], default='enabled', max_length=10, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'db_table': 'packages',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('per_call', '按次计费'), ('per_unit', '按量计费'), ('free', '免费')], default='per_call', max_length=10, verbose_name='计费方式')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='单价(元)')),
                ('min_level', models.IntegerField(default=1, verbose_name='最低会员等级')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='规则说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计费规则',
                'verbose_name_plural': '计费规则',
                'db_table': 'pricing_rules',
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额(元)')),
                ('pay_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付')], default='alipay', max_length=10, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
                'db_table': 'recharge_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='兑换码')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(元)')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('batch_no', models.CharField(blank=True, max_length=32, verbose_name='批次号')),
            ],
            options={
                'verbose_name': '兑换码',
                'verbose_name_plural': '兑换码',
                'db_table': 'redeem_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recharge', '充值'), ('consume', '消费'), ('commission', '佣金'), ('refund', '退款'), ('adjust', '调整')], max_length=10, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(元)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易后余额')),
                ('description', models.CharField(max_length=255, verbose_name='交易描述')),
                ('related_order', models.CharField(blank=True, max_length=32, verbose_name='关联订单号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('calls_used', models.IntegerField(default=0, verbose_name='已用调用次数')),
                ('tokens_used', models.BigIntegerField(default=0, verbose_name='已用Token量')),
                ('status', models.CharField(choices=[('active', '使用中'), ('expired', '已过期'), ('used_up', '已用完')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='购买时间')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.package', verbose_name='套餐')),
            ],
            options={
                'verbose_name': '用户套餐',
                'verbose_name_plural': '用户套餐',
                'db_table': 'user_packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
