# Generated by Django 3.2.25 on 2026-06-21 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('code', models.CharField(max_length=50, verbose_name='模型编码')),
                ('icon', models.CharField(blank=True, default='', max_length=255, verbose_name='图标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('servlet_path', models.CharField(max_length=255, verbose_name='接口路径')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10, verbose_name='请求方法')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=10, verbose_name='状态')),
                ('bill_type', models.CharField(choices=[('per_call', '按次计费'), ('per_unit', '按量计费'), ('free', '免费')], default='per_call', max_length=10, verbose_name='计费方式')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='单价(元)')),
                ('unit_type', models.CharField(blank=True, choices=[('', '不适用'), ('per_1k', '千tokens (K)'), ('per_1m', '百万tokens (M)')], default='', max_length=10, verbose_name='计量单位')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API模型',
                'verbose_name_plural': 'API模型',
                'db_table': 'api_models',
                'ordering': ['channel', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ApiParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=100, verbose_name='参数名')),
                ('param_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('number', '数字'), ('boolean', '布尔'), ('array', '数组'), ('object', '对象')], default='string', max_length=10, verbose_name='参数类型')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('default_value', models.CharField(blank=True, max_length=500, verbose_name='默认值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='参数说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'API参数',
                'verbose_name_plural': 'API参数',
                'db_table': 'api_parameters',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='渠道名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='渠道编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('base_url', models.CharField(max_length=255, verbose_name='基础URL')),
                ('auth_type', models.CharField(choices=[('hmac', 'AK/SK签名'), ('bearer', 'Bearer Token')], default='hmac', max_length=10, verbose_name='认证方式')),
                ('access_key', models.CharField(blank=True, default='', max_length=128, verbose_name='AccessKey')),
                ('secret_key', models.CharField(blank=True, default='', max_length=128, verbose_name='SecretKey')),
                ('api_key', models.CharField(blank=True, default='', max_length=256, verbose_name='API Key (Bearer)')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=10, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '渠道',
                'verbose_name_plural': '渠道',
                'db_table': 'channels',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('response_state', models.CharField(blank=True, max_length=20, verbose_name='响应状态')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='费用')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='调用时间')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apimodels.channel', verbose_name='渠道')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apimodels.apimodel', verbose_name='API模型')),
            ],
            options={
                'verbose_name': 'API调用日志',
                'verbose_name_plural': 'API调用日志',
                'db_table': 'api_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
