# Generated by Django 3.2.25 on 2026-06-21 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apimodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='apiparameter',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='apimodels.apimodel', verbose_name='所属模型'),
        ),
        migrations.AddField(
            model_name='apimodel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_models', to='apimodels.channel', verbose_name='所属渠道'),
        ),
        migrations.AlterUniqueTogether(
            name='apimodel',
            unique_together={('channel', 'code')},
        ),
    ]
