# Generated by Django 3.2.25 on 2026-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimodels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='task_type',
            field=models.CharField(choices=[('chat', '对话'), ('video', '视频生成')], default='chat', max_length=10, verbose_name='任务类型'),
        ),
    ]
