# Generated by Django 3.2.25 on 2026-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimodels', '0003_apimodel_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='能力编码')),
                ('name', models.CharField(max_length=50, verbose_name='能力名称')),
                ('icon', models.CharField(default='', max_length=10, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '模型能力',
                'verbose_name_plural': '模型能力',
                'db_table': 'capabilities',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='apimodel',
            name='duration_options',
            field=models.JSONField(blank=True, default=list, verbose_name='时长定价'),
        ),
        migrations.AddField(
            model_name='apimodel',
            name='resolution_options',
            field=models.JSONField(blank=True, default=list, verbose_name='分辨率定价'),
        ),
        migrations.AddField(
            model_name='apimodel',
            name='capabilities',
            field=models.ManyToManyField(blank=True, to='apimodels.Capability', verbose_name='模型能力'),
        ),
    ]
