# Generated by Django 3.2.25 on 2026-06-21 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '一级代理'), (2, '二级代理'), (3, '三级代理')], default=1, verbose_name='代理等级')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='佣金比例(%)')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计佣金')),
                ('member_count', models.IntegerField(default=0, verbose_name='下级会员数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='成为代理时间')),
            ],
            options={
                'verbose_name': '代理信息',
                'verbose_name_plural': '代理信息',
                'db_table': 'agent_profiles',
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20, verbose_name='来源类型')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单金额')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='佣金比例(%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='佣金金额')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('settled', '已结算')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='产生时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
            ],
            options={
                'verbose_name': '佣金记录',
                'verbose_name_plural': '佣金记录',
                'db_table': 'commission_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='提现金额')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('review_remark', models.CharField(blank=True, max_length=255, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agentprofile', verbose_name='代理')),
            ],
            options={
                'verbose_name': '提现申请',
                'verbose_name_plural': '提现申请',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
