# Generated by Django 3.2.25 on 2026-06-21 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_url', models.CharField(max_length=500, verbose_name='请求URL')),
                ('request_params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('response_state', models.CharField(max_length=20, verbose_name='响应状态')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='本次费用')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='调用前余额')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='调用后余额')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('pending', '处理中'), ('blocked', '已拦截')], default='pending', max_length=10, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('filter_hits', models.TextField(blank=True, verbose_name='敏感词命中')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='调用时间')),
            ],
            options={
                'verbose_name': 'API请求记录',
                'verbose_name_plural': 'API请求记录',
                'db_table': 'api_request_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='敏感词')),
                ('level', models.CharField(choices=[('block', '拦截'), ('replace', '替换'), ('audit', '审核')], default='replace', max_length=10, verbose_name='处理级别')),
                ('replacement', models.CharField(default='***', max_length=50, verbose_name='替换文本')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
                'db_table': 'sensitive_words',
                'ordering': ['-created_at'],
            },
        ),
    ]
