# Generated by Django 3.2.25 on 2026-06-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apigateway', '0001_initial'),
        ('apimodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestrecord',
            name='api_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apimodels.apimodel', verbose_name='API模型'),
        ),
    ]
