# Generated by Django 3.2.25 on 2026-06-26 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apimodels', '0003_apimodel_task_type'),
        ('apigateway', '0003_apirequestrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_task_id', models.CharField(max_length=128, unique=True, verbose_name='远端任务ID')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '生成中'), ('succeeded', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('prompt_text', models.TextField(blank=True, verbose_name='提示词')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求参数')),
                ('video_url', models.CharField(blank=True, max_length=500, verbose_name='视频URL')),
                ('local_path', models.CharField(blank=True, max_length=500, verbose_name='本地路径')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apimodels.apimodel', verbose_name='模型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '视频生成任务',
                'verbose_name_plural': '视频生成任务',
                'db_table': 'video_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
