# Generated by Django 3.2.25 on 2026-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0004_videotask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotask',
            name='remote_task_id',
            field=models.CharField(max_length=128, verbose_name='远端任务ID'),
        ),
    ]
