# Generated by Django 3.2.25 on 2026-06-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0005_fix_videotask_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestrecord',
            name='completion_tokens',
            field=models.IntegerField(default=0, verbose_name='生成Token'),
        ),
        migrations.AddField(
            model_name='apirequestrecord',
            name='prompt_tokens',
            field=models.IntegerField(default=0, verbose_name='提示Token'),
        ),
    ]
